version: '3'
services:
  app:
    build:
      context: app/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/sqlite_data
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './redis_data'
  sqlite_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './sqlite_data'
